[application]
name = "dioxus_leaflet"
default_platform = "web"

[application.plugins]

[web.app]
title = "Dioxus Leaflet"

[web.wasm_opt]
level = "s"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
